apiVersion: extensions/v1beta1
kind: Deployment
metedata:
  name: influxdb-deploy
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: influxdb
    replicas: 2
    template:
      metadata:
        labels:
          app: influxdb
        name: influxdb
        namespace: kube-system
      spec:
        containers:
        - name: influxdb
          image: registry.xxx.com.cn/data/influxdb-enableauth:v1.3.3
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8086
            hostPort: 8086
            protocol: TCP
          volumeMounts:
          - mountPath: /data
            name: influxdb-storage
            nodeSelector:
              disk: big
            volumes:
            - name: influxdb-storage
              hostPath:
                path: /data7/influxdb 
